# -*- coding: utf-8 -*-
"""KEAM_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OThGgS7jqpFfI29Zncp1oVgbPFSl-PBz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from flask import Flask, jsonify

app = Flask(__name__)

cllg_sort_path = r"C:\Users\mznch\KEAM-Predictor\cllg_sort.csv"
df_path = r"C:\Users\mznch\KEAM-Predictor\df.csv"

cllg_sort = pd.read_csv(cllg_sort_path)
df = pd.read_csv(df_path)

@app.route('/predict/<int:rank>/<int:i>/<string:bestCollege_Pred>')
@app.route('/predict/<int:rank>/<int:i>')
def predict(rank,i,bestCollege_Pred="False"):
    bestCollegePred = bestCollege_Pred.lower() == "true"
    print(bestCollege_Pred)
    print(bestCollegePred)
    if(bestCollegePred):
      filtered_df = cllg_sort[cllg_sort['Rank'] >= rank]
      print(filtered_df)
    else:
      filtered_df = df[df['Rank'] >= rank]
      print(filtered_df)
    result = filtered_df[["College","Branch"]][:i].reset_index(drop = True)
    result_dict = result.to_dict(orient = "list")
    print(result_dict)
    return jsonify(result_dict)

@app.route('/predict_by_college/<int:rank>/<int:i>/<string:college>')
def predict_by_college(rank,i,college):
  filtered_df = cllg_sort.loc[(cllg_sort["College"]==college)&(cllg_sort["Rank"]>rank)]
  result_dict = filtered_df[["College","Branch"]][:i].reset_index(drop = True).to_dict(orient="list")
  print(result_dict)
  return jsonify(result_dict)


if __name__ == '__main__':
    app.run()

predict(500,3)